<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE database [
        <!ELEMENT database (tables)>
        <!ATTLIST database
                name CDATA #REQUIRED
                desc CDATA #REQUIRED>
        <!ELEMENT tables (table)+>
        <!ELEMENT table (columns)>
        <!ATTLIST table
                desc CDATA #REQUIRED
                name CDATA #REQUIRED>
        <!ELEMENT columns (column)+>
        <!ELEMENT column EMPTY>
        <!ATTLIST column
                decimalLen CDATA #IMPLIED
                desc CDATA #REQUIRED
                len CDATA #IMPLIED
                name CDATA #REQUIRED
                nullable (true|false) "false"
                primaryKey (true|false) "false"
                dictCode CDATA #IMPLIED
                unique CDATA #IMPLIED
                foreignKey CDATA #IMPLIED
                type (long|text|int|longtext|float) #REQUIRED >
        ]>
<database name="ywk" desc="一网考数据库">
    <tables>
        <table name="t_manager" desc="后台管理员信息表">
            <columns>
                <column name="id" type="long" desc="主键" primaryKey="true"/>
                <column name="username" type="text" len="40" desc="账号" unique="account"/>
                <column name="password" type="text" len="100" desc="密码"/>
                <column name="last_ip" type="text" len="20" desc="最后登录IP" nullable="true"/>
                <column name="last_login_time" type="long" desc="最后登录时间" nullable="true"/>
                <column name="create_time" type="long" desc="创建时间"/>
            </columns>
        </table>
        <table name="t_news_category" desc="新闻-栏目信息">
            <columns>
                <column name="id" type="long" desc="主键" primaryKey="true"/>
                <column name="name" type="text" len="20" desc="栏目名称"/>
                <column name="code" type="text" len="10" desc="栏目编码" unique="code"/>
                <column name="create_time" type="long" desc="创建时间"/>
            </columns>
        </table>
        <table name="t_news_article" desc="新闻-文章信息">
            <columns>
                <column name="id" type="long" desc="主键" primaryKey="true"/>
                <column name="category_id" type="long" desc="所属栏目" foreignKey="t_news_category.id"/>
                <column name="title" type="text" len="100" desc="文章标题"/>
                <column name="brief" type="text" len="300" desc="文章简介" nullable="true"/>
                <column name="picture_address" type="text" len="300" desc="文章题图地址" nullable="true"/>
                <column name="content" type="longtext" desc="文章内容"/>
                <column name="carousel" type="int" desc="是否首页轮播" dictCode="yes_or_no"/>
                <column name="creator" type="long" desc="发布人" foreignKey="t_manager.id"/>
                <column name="create_time" type="long" desc="创建时间"/>
                <column name="update_time" type="long" desc="更新时间"/>
            </columns>
        </table>
        <table name="t_data_dict" desc="数据字典表">
            <columns>
                <column name="id" type="long" desc="主键" primaryKey="true"/>
                <column name="rid" type="long" desc="根字典id。没有为0"/>
                <column name="pid" type="long" desc="上级字典id。没有为0" unique="dict"/>
                <column name="code" type="text" len="50" desc="字典编码" unique="dict"/>
                <column name="description" type="text" len="300" desc="字典描述" unique="desc11"/>
                <column name="order_flag" type="int" desc="排序序号。小的优先级高。"/>
                <column name="create_time" type="long" desc="创建时间"/>
                <column name="update_time" type="long" desc="更新时间"/>
            </columns>
        </table>
        <table name="t_operate_log" desc="操作日志表">
            <columns>
                <column name="id" type="long" desc="主键" primaryKey="true"/>
                <column name="operator" type="long" desc="操作人" foreignKey="t_manager.id"/>
                <column name="type" type="int" desc="操作类型" dictCode="manager_operate_type"/>
                <column name="note" type="text" len="100" desc="操作说明" nullable="true"/>
                <column name="create_time" type="long" desc="创建时间"/>
            </columns>
        </table>
    </tables>
</database>